'use server';

import { createClient } from '@/utils/supabase/server';
import type { Room, Player, RoomStatus } from '@/types/database';

/**
 * Server Action: Create a new game room
 *
 * Creates a room in Postgres and returns the room code.
 * The current user becomes the host.
 */
export async function createRoom(): Promise<{ code: string } | { error: string }> {
  const supabase = await createClient();

  // Get current user
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return { error: 'You must be logged in to create a room' };
  }

  // Create the room - code is auto-generated by the database
  const { data: room, error: roomError } = await supabase
    .from('rooms')
    .insert({
      host_id: user.id,
      status: 'waiting' as RoomStatus,
      current_round_index: 0,
    })
    .select('id, code')
    .single();

  if (roomError) {
    console.error('Error creating room:', roomError);
    return { error: 'Failed to create room. Please try again.' };
  }

  // Get user display name from metadata
  const displayName =
    user.user_metadata?.full_name ||
    user.user_metadata?.name ||
    user.email?.split('@')[0] ||
    'Host';

  // Add the host as a player in the room
  const { error: playerError } = await supabase.from('players').insert({
    room_id: room.id,
    user_id: user.id,
    display_name: displayName,
    avatar_url: user.user_metadata?.avatar_url || null,
    score: 0,
  });

  if (playerError) {
    console.error('Error adding host as player:', playerError);
    // Don't fail the room creation, just log the error
  }

  return { code: room.code };
}

/**
 * Server Action: Join an existing room by code
 */
export async function joinRoom(
  code: string
): Promise<{ roomId: string } | { error: string }> {
  const supabase = await createClient();

  // Get current user
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return { error: 'You must be logged in to join a room' };
  }

  // Find the room by code
  const { data: room, error: roomError } = await supabase
    .from('rooms')
    .select('id, status')
    .eq('code', code.toUpperCase())
    .single();

  if (roomError || !room) {
    return { error: 'Room not found. Check the code and try again.' };
  }

  if (room.status !== 'waiting') {
    return { error: 'This game has already started.' };
  }

  // Check if user is already in the room
  const { data: existingPlayer } = await supabase
    .from('players')
    .select('id')
    .eq('room_id', room.id)
    .eq('user_id', user.id)
    .single();

  if (existingPlayer) {
    // User is already in the room, just return the room ID
    return { roomId: room.id };
  }

  // Get user display name from metadata
  const displayName =
    user.user_metadata?.full_name ||
    user.user_metadata?.name ||
    user.email?.split('@')[0] ||
    'Player';

  // Add user as a player
  const { error: playerError } = await supabase.from('players').insert({
    room_id: room.id,
    user_id: user.id,
    display_name: displayName,
    avatar_url: user.user_metadata?.avatar_url || null,
    score: 0,
  });

  if (playerError) {
    console.error('Error joining room:', playerError);
    return { error: 'Failed to join room. Please try again.' };
  }

  return { roomId: room.id };
}

/**
 * Server Action: Get room details by code
 */
export async function getRoomByCode(
  code: string
): Promise<{ room: Room; players: Player[] } | { error: string }> {
  const supabase = await createClient();

  // Find the room by code
  const { data: room, error: roomError } = await supabase
    .from('rooms')
    .select('*')
    .eq('code', code.toUpperCase())
    .single();

  if (roomError || !room) {
    return { error: 'Room not found' };
  }

  // Get all players in the room
  const { data: players, error: playersError } = await supabase
    .from('players')
    .select('*')
    .eq('room_id', room.id)
    .order('joined_at', { ascending: true });

  if (playersError) {
    return { error: 'Failed to load players' };
  }

  return { room: room as Room, players: (players || []) as Player[] };
}

/**
 * Server Action: Update room status (host only)
 */
export async function updateRoomStatus(
  roomId: string,
  status: Room['status'],
  currentRoundIndex?: number
): Promise<{ success: boolean } | { error: string }> {
  const supabase = await createClient();

  // Get current user
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return { error: 'You must be logged in' };
  }

  // RLS will ensure only the host can update
  const updateData: { status: RoomStatus; current_round_index?: number } = { status };
  if (currentRoundIndex !== undefined) {
    updateData.current_round_index = currentRoundIndex;
  }

  const { error: updateError } = await supabase
    .from('rooms')
    .update(updateData)
    .eq('id', roomId)
    .eq('host_id', user.id); // Extra safety check

  if (updateError) {
    console.error('Error updating room:', updateError);
    return { error: 'Failed to update room status' };
  }

  return { success: true };
}

/**
 * Server Action: Update player score (host only)
 */
export async function updatePlayerScore(
  playerId: string,
  scoreToAdd: number
): Promise<{ success: boolean } | { error: string }> {
  const supabase = await createClient();

  // Get current player to update score
  const { data: player, error: playerError } = await supabase
    .from('players')
    .select('score, room_id')
    .eq('id', playerId)
    .single();

  if (playerError || !player) {
    return { error: 'Player not found' };
  }

  // Update the score
  const { error: updateError } = await supabase
    .from('players')
    .update({ score: (player.score as number) + scoreToAdd })
    .eq('id', playerId);

  if (updateError) {
    console.error('Error updating score:', updateError);
    return { error: 'Failed to update score' };
  }

  return { success: true };
}

/**
 * Server Action: Leave a room
 */
export async function leaveRoom(roomId: string): Promise<{ success: boolean } | { error: string }> {
  const supabase = await createClient();

  // Get current user
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return { error: 'You must be logged in' };
  }

  // Delete the player record
  const { error: deleteError } = await supabase
    .from('players')
    .delete()
    .eq('room_id', roomId)
    .eq('user_id', user.id);

  if (deleteError) {
    console.error('Error leaving room:', deleteError);
    return { error: 'Failed to leave room' };
  }

  return { success: true };
}
