'use server';

import { createClient } from '@/utils/supabase/server';
import { cookies } from 'next/headers';
import { v4 as uuidv4 } from 'uuid';
import type { Room, Player, RoomStatus } from '@/types/database';

/**
 * Server Action: Create a new game room
 *
 * Creates a room in Postgres and returns the room code.
 * The current user becomes the host.
 */
export async function createRoom(): Promise<{ code: string } | { error: string }> {
  const supabase = await createClient();

  // Get current user
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return { error: 'You must be logged in to create a room' };
  }

  // Create the room - code is auto-generated by the database
  const { data: room, error: roomError } = await supabase
    .from('rooms')
    .insert({
      host_id: user.id,
      status: 'waiting' as RoomStatus,
      current_round_index: 0,
    })
    .select('id, code')
    .single();

  if (roomError) {
    console.error('Error creating room:', roomError);
    return { error: 'Failed to create room. Please try again.' };
  }

  // Get user display name from metadata
  const displayName =
    user.user_metadata?.full_name ||
    user.user_metadata?.name ||
    user.email?.split('@')[0] ||
    'Host';

  // Add the host as a player in the room
  const { error: playerError } = await supabase.from('players').insert({
    room_id: room.id,
    user_id: user.id,
    display_name: displayName,
    avatar_url: user.user_metadata?.avatar_url || null,
    score: 0,
  });

  if (playerError) {
    console.error('Error adding host as player:', playerError);
    // Don't fail the room creation, just log the error
  }

  return { code: room.code };
}

/**
 * Server Action: Join an existing room by code
 */
export async function joinRoom(
  code: string
): Promise<{ roomId: string } | { error: string }> {
  const supabase = await createClient();

  // Get current user
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return { error: 'You must be logged in to join a room' };
  }

  // Find the room by code
  const { data: room, error: roomError } = await supabase
    .from('rooms')
    .select('id, status')
    .eq('code', code.toUpperCase())
    .single();

  if (roomError || !room) {
    return { error: 'Room not found. Check the code and try again.' };
  }

  if (room.status !== 'waiting') {
    return { error: 'This game has already started.' };
  }

  // Check if user is already in the room
  const { data: existingPlayer } = await supabase
    .from('players')
    .select('id')
    .eq('room_id', room.id)
    .eq('user_id', user.id)
    .single();

  if (existingPlayer) {
    // User is already in the room, just return the room ID
    return { roomId: room.id };
  }

  // Get user display name from metadata
  const displayName =
    user.user_metadata?.full_name ||
    user.user_metadata?.name ||
    user.email?.split('@')[0] ||
    'Player';

  // Add user as a player
  const { error: playerError } = await supabase.from('players').insert({
    room_id: room.id,
    user_id: user.id,
    display_name: displayName,
    avatar_url: user.user_metadata?.avatar_url || null,
    score: 0,
  });

  if (playerError) {
    console.error('Error joining room:', playerError);
    return { error: 'Failed to join room. Please try again.' };
  }

  return { roomId: room.id };
}

/**
 * Server Action: Join a room as a guest (no Spotify account required)
 */
export async function joinRoomAsGuest(
  code: string,
  nickname: string
): Promise<{ roomId: string; guestId: string } | { error: string }> {
  // Validate nickname
  const trimmedNickname = nickname.trim();
  if (!trimmedNickname || trimmedNickname.length < 2) {
    return { error: 'El nombre debe tener al menos 2 caracteres' };
  }
  if (trimmedNickname.length > 20) {
    return { error: 'El nombre no puede tener más de 20 caracteres' };
  }

  const supabase = await createClient();

  // Find the room by code
  const { data: room, error: roomError } = await supabase
    .from('rooms')
    .select('id, status')
    .eq('code', code.toUpperCase())
    .single();

  if (roomError || !room) {
    return { error: 'Sala no encontrada. Verifica el código.' };
  }

  if (room.status !== 'waiting') {
    return { error: 'Este juego ya ha comenzado.' };
  }

  // Generate a guest ID
  const guestId = uuidv4();

  // Check if this guest is already in the room (by checking cookies)
  const cookieStore = await cookies();
  const existingGuestId = cookieStore.get('guest_id')?.value;

  if (existingGuestId) {
    // Check if this guest is already a player in this room
    const { data: existingPlayer } = await supabase
      .from('players')
      .select('id')
      .eq('room_id', room.id)
      .eq('guest_id', existingGuestId)
      .single();

    if (existingPlayer) {
      // Update the guest name if needed
      await supabase
        .from('players')
        .update({ display_name: trimmedNickname })
        .eq('id', existingPlayer.id);

      // Update cookies
      cookieStore.set('guest_name', trimmedNickname, {
        httpOnly: true,
        secure: process.env.NODE_ENV === 'production',
        sameSite: 'lax',
        maxAge: 60 * 60 * 24, // 24 hours
      });

      return { roomId: room.id, guestId: existingGuestId };
    }
  }

  // Add guest as a player
  const { error: playerError } = await supabase.from('players').insert({
    room_id: room.id,
    user_id: null,
    guest_id: guestId,
    display_name: trimmedNickname,
    avatar_url: null,
    score: 0,
  });

  if (playerError) {
    console.error('Error adding guest player:', playerError);
    return { error: 'Error al unirse a la sala. Intenta de nuevo.' };
  }

  // Set cookies for guest session
  cookieStore.set('guest_id', guestId, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    maxAge: 60 * 60 * 24, // 24 hours
  });

  cookieStore.set('guest_name', trimmedNickname, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    maxAge: 60 * 60 * 24, // 24 hours
  });

  cookieStore.set('guest_room_id', room.id, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    maxAge: 60 * 60 * 24, // 24 hours
  });

  return { roomId: room.id, guestId };
}

/**
 * Server Action: Get current guest info from cookies
 */
export async function getGuestSession(): Promise<{
  guestId: string;
  guestName: string;
  roomId: string;
} | null> {
  const cookieStore = await cookies();
  const guestId = cookieStore.get('guest_id')?.value;
  const guestName = cookieStore.get('guest_name')?.value;
  const roomId = cookieStore.get('guest_room_id')?.value;

  if (guestId && guestName && roomId) {
    return { guestId, guestName, roomId };
  }
  return null;
}

/**
 * Server Action: Clear guest session
 */
export async function clearGuestSession(): Promise<void> {
  const cookieStore = await cookies();
  cookieStore.delete('guest_id');
  cookieStore.delete('guest_name');
  cookieStore.delete('guest_room_id');
}

/**
 * Server Action: Get room details by code
 */
export async function getRoomByCode(
  code: string
): Promise<{ room: Room; players: Player[] } | { error: string }> {
  const supabase = await createClient();

  // Find the room by code
  const { data: room, error: roomError } = await supabase
    .from('rooms')
    .select('*')
    .eq('code', code.toUpperCase())
    .single();

  if (roomError || !room) {
    return { error: 'Room not found' };
  }

  // Get all players in the room
  const { data: players, error: playersError } = await supabase
    .from('players')
    .select('*')
    .eq('room_id', room.id)
    .order('joined_at', { ascending: true });

  if (playersError) {
    return { error: 'Failed to load players' };
  }

  return { room: room as Room, players: (players || []) as Player[] };
}

/**
 * Server Action: Update room status (host only)
 */
export async function updateRoomStatus(
  roomId: string,
  status: Room['status'],
  currentRoundIndex?: number
): Promise<{ success: boolean } | { error: string }> {
  const supabase = await createClient();

  // Get current user
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return { error: 'You must be logged in' };
  }

  // RLS will ensure only the host can update
  const updateData: { status: RoomStatus; current_round_index?: number } = { status };
  if (currentRoundIndex !== undefined) {
    updateData.current_round_index = currentRoundIndex;
  }

  const { error: updateError } = await supabase
    .from('rooms')
    .update(updateData)
    .eq('id', roomId)
    .eq('host_id', user.id); // Extra safety check

  if (updateError) {
    console.error('Error updating room:', updateError);
    return { error: 'Failed to update room status' };
  }

  return { success: true };
}

/**
 * Server Action: Update player score (host only)
 */
export async function updatePlayerScore(
  playerId: string,
  scoreToAdd: number
): Promise<{ success: boolean } | { error: string }> {
  const supabase = await createClient();

  // Get current player to update score
  const { data: player, error: playerError } = await supabase
    .from('players')
    .select('score, room_id')
    .eq('id', playerId)
    .single();

  if (playerError || !player) {
    return { error: 'Player not found' };
  }

  // Update the score
  const { error: updateError } = await supabase
    .from('players')
    .update({ score: (player.score as number) + scoreToAdd })
    .eq('id', playerId);

  if (updateError) {
    console.error('Error updating score:', updateError);
    return { error: 'Failed to update score' };
  }

  return { success: true };
}

/**
 * Server Action: Leave a room
 */
export async function leaveRoom(roomId: string): Promise<{ success: boolean } | { error: string }> {
  const supabase = await createClient();

  // Get current user
  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError || !user) {
    return { error: 'You must be logged in' };
  }

  // Delete the player record
  const { error: deleteError } = await supabase
    .from('players')
    .delete()
    .eq('room_id', roomId)
    .eq('user_id', user.id);

  if (deleteError) {
    console.error('Error leaving room:', deleteError);
    return { error: 'Failed to leave room' };
  }

  return { success: true };
}
